const citasMotivacionales = [
  { cita: "Believe you can and you’re halfway there.", autor: "Theodore Roosevelt" },
  { cita: "Don’t watch the clock; do what it does. Keep going.", autor: "Sam Levenson" },
  { cita: "The harder you work for something, the greater you’ll feel when you achieve it.", autor: "Unknown" },
  { cita: "Dream it. Wish it. Do it.", autor: "Unknown" },
  { cita: "Success doesn’t just find you. You have to go out and get it.", autor: "Unknown" },
  { cita: "Don’t stop when you’re tired. Stop when you’re done.", autor: "Unknown" },
  { cita: "Little things make big days.", autor: "Unknown" },
  { cita: "It always seems impossible until it’s done.", autor: "Nelson Mandela" },
  { cita: "Push yourself, because no one else is going to do it for you.", autor: "Unknown" },
  { cita: "Great things never come from comfort zones.", autor: "Unknown" },
  { cita: "Dream bigger. Do bigger.", autor: "Unknown" },
  { cita: "Wake up with determination. Go to bed with satisfaction.", autor: "Unknown" },
  { cita: "Do something today that your future self will thank you for.", autor: "Unknown" },
  { cita: "Little progress is still progress.", autor: "Unknown" },
  { cita: "Don’t wait for opportunity. Create it.", autor: "Unknown" },
  { cita: "The key to success is to focus on goals, not obstacles.", autor: "Unknown" },
  { cita: "Success is the sum of small efforts repeated day in and day out.", autor: "Robert Collier" },
  { cita: "Your limitation—it’s only your imagination.", autor: "Unknown" },
  { cita: "Stay positive, work hard, make it happen.", autor: "Unknown" },
  { cita: "Believe in yourself and all that you are.", autor: "Unknown" },
  { cita: "If it doesn’t challenge you, it won’t change you.", autor: "Unknown" },
  { cita: "Strive for progress, not perfection.", autor: "Unknown" },
  { cita: "Don’t wait for the perfect moment. Take the moment and make it perfect.", autor: "Unknown" },
  { cita: "Difficult roads often lead to beautiful destinations.", autor: "Unknown" },
  { cita: "Your only limit is your mind.", autor: "Unknown" },
  { cita: "Sometimes later becomes never. Do it now.", autor: "Unknown" },
  { cita: "Great things never come from comfort zones.", autor: "Unknown" },
  { cita: "The secret of getting ahead is getting started.", autor: "Mark Twain" },
  { cita: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", autor: "Roy T. Bennett" },
  { cita: "Success is not for the lazy.", autor: "Unknown" },
  { cita: "Don’t quit. Suffer now and live the rest of your life as a champion.", autor: "Muhammad Ali" },
  { cita: "Hustle until your haters ask if you’re hiring.", autor: "Unknown" },
  { cita: "You don’t have to be great to start, but you have to start to be great.", autor: "Zig Ziglar" },
  { cita: "Do what you can with what you have, where you are.", autor: "Theodore Roosevelt" },
  { cita: "The best way to get started is to quit talking and begin doing.", autor: "Walt Disney" },
  { cita: "Success usually comes to those who are too busy to be looking for it.", autor: "Henry David Thoreau" },
  { cita: "Don’t let yesterday take up too much of today.", autor: "Will Rogers" },
  { cita: "You are never too old to set another goal or to dream a new dream.", autor: "C.S. Lewis" },
  { cita: "Opportunities don’t happen. You create them.", autor: "Chris Grosser" },
  { cita: "It always seems impossible until it’s done.", autor: "Nelson Mandela" },
  { cita: "Start where you are. Use what you have. Do what you can.", autor: "Arthur Ashe" },
  { cita: "Don’t be afraid to give up the good to go for the great.", autor: "John D. Rockefeller" },
  { cita: "Success is not in what you have, but who you are.", autor: "Bo Bennett" },
  { cita: "Act as if what you do makes a difference. It does.", autor: "William James" },
  { cita: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", autor: "Chantal Sutherland" },
  { cita: "What seems to us as bitter trials are often blessings in disguise.", autor: "Oscar Wilde" },
  { cita: "The only way to do great work is to love what you do.", autor: "Steve Jobs" },
  { cita: "Success is walking from failure to failure with no loss of enthusiasm.", autor: "Winston Churchill" },
  { cita: "Your life does not get better by chance, it gets better by change.", autor: "Jim Rohn" },
  { cita: "Push yourself, because no one else is going to do it for you.", autor: "Unknown" },
  { cita: "Don’t limit your challenges. Challenge your limits.", autor: "Unknown" }
];
